version: "3.7"

services:

  redis:
    build:
      context: ./
    image: unbmaster/redis:1.0
    container_name: redis
    command: redis-server --requirepass 12345 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - app-data:/data
    restart: always
    networks:
      - app-net

networks:
  app-net:
    external: true

volumes:
  app-data: